name: Generate Documentation

on:
  pull_request:
  push:
    branches:
    - master

jobs:
  mkdocs:
    name: MkDocs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Project
      uses: actions/checkout@v2

    - name: Install MkDocs and Dependencies
      run: pip install -r docs/requirements.txt

    - name: Build Docs
      run: mkdocs build

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: mkdocs-site
        path: site

    - name: Deploy Docs
      if: github.event_name == 'push'
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: site
